name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, macos-latest]
        ruby: ['3.1', '3.2', '3.3']
        rust: [stable]

    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
        bundler-cache: true

    - name: Set up Rust
      uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: ${{ matrix.rust }}

    - name: Install dependencies
      run: bundle install

    - name: Compile extension
      run: bundle exec rake compile

    - name: Run tests
      run: bundle exec rspec

    - name: Run linter (Ruby 3.3 only)
      if: matrix.ruby == '3.3'
      run: bundle exec rake standard

  build-musl:
    runs-on: ubuntu-latest
    container:
      image: rust:alpine
    steps:
    - uses: actions/checkout@v4

    - name: Install build dependencies
      run: |
        apk add --no-cache build-base ruby ruby-dev

    - name: Install bundler
      run: gem install bundler

    - name: Install dependencies
      run: bundle install

    - name: Compile extension
      run: bundle exec rake compile

    - name: Run tests
      run: bundle exec rspec